# -*- coding: utf-8 -*-
"""01_midi_exploration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1voQXwGxzBGwjnJoQsH7nc_WOzUNIQw5t

# 01 – MIDI Exploration (Classical Piano / MAESTRO)
**Project**: [MIDI Music Generation](https://github.com/S33mi/midi-music-generation)  
**Author**: [S33mi](https://github.com/S33mi/)  

Explore the **MAESTRO** classical piano MIDI dataset, inspect note structure, and prepare intuition for sequence modeling in later notebooks.

Dataset: MAESTRO v2 MIDI-only (~56 MB) – standard for piano generation tutorials.

## 1. Setup & Imports

Run Once if needed
```
!pip install pretty_midi
# Optional
!pip install pretty_midi mido music21
```
"""

# !pip install pretty_midi

# !pip install pretty_midi mido music21

import os
import glob
import pathlib
import shutil # added
import collections
from collections import Counter

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pretty_midi
import tensorflow as tf
from tqdm.auto import tqdm
import warnings


warnings.filterwarnings("ignore")
sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (12, 5)

print("TensorFlow:", tf.__version__)
print("pretty_midi ready.")

"""## 2. Download MAESTRO MIDI (Colab / local)

"""

DATA_DIR = pathlib.Path("data/maestro-v2.0.0")
ZIP_NAME = "maestro-v2.0.0-midi.zip"
URL = "https://storage.googleapis.com/magentadata/datasets/maestro/v2.0.0/maestro-v2.0.0-midi.zip"

# Clean previous broken attempts
if DATA_DIR.exists():
    shutil.rmtree(DATA_DIR)
if pathlib.Path("data").exists():
    # also remove the cached zip if present
    zip_path = pathlib.Path("data") / ZIP_NAME
    if zip_path.exists():
        zip_path.unlink()

print("Downloading MAESTRO MIDI (~56 MB) ...")
tf.keras.utils.get_file(
    fname=ZIP_NAME,
    origin=URL,
    extract=True,
    cache_dir=".",
    cache_subdir="data",
)
print("Download + extract done.")

# Check where files landed
print("\nAfter extract – contents of data/:")
!ls -la data/

# The zip usually extracts to data/maestro-v2.0.0/
# but sometimes the year folders end up directly under data/
if not DATA_DIR.exists():
    # Try the alternative structure
    possible = list(pathlib.Path("data").glob("**/2004"))
    if possible:
        print("Found year folders under:", possible[0].parent)
        DATA_DIR = possible[0].parent
    else:
        print("Still cannot locate maestro folder. Paste the output of the diagnostic cell above.")


# List MIDI files
filenames = sorted(glob.glob(str(DATA_DIR / "**" / "*.mid*"), recursive=True))
print(f"\nNumber of MIDI files: {len(filenames)}")
print("Example paths:")
for p in filenames[:5]:
    print(" ", p)

"""## 3. Inspect a Single MIDI File

"""

sample_file = filenames[0]
print("Sample file:", sample_file)

pm = pretty_midi.PrettyMIDI(sample_file)

print("\n--- Basic info ---")
print(f"Duration (s)     : {pm.get_end_time():.1f}")
print(f"Instruments      : {len(pm.instruments)}")
for i, inst in enumerate(pm.instruments):
    print(f"  [{i}] program={inst.program}, is_drum={inst.is_drum}, name={inst.name!r}, notes={len(inst.notes)}")

# Use first non-drum instrument
piano = None
for inst in pm.instruments:
    if not inst.is_drum:
        piano = inst
        break

if piano is None:
    raise RuntimeError("No non-drum instrument found in sample file.")

print(f"\nUsing instrument: program={piano.program}, notes={len(piano.notes)}")

"""### First few notes

"""

notes_preview = []
for n in piano.notes[:15]:
    notes_preview.append({
        "pitch": n.pitch,
        "pitch_name": pretty_midi.note_number_to_name(n.pitch),
        "start": round(n.start, 3),
        "end": round(n.end, 3),
        "duration": round(n.end - n.start, 3),
        "velocity": n.velocity,
    })

pd.DataFrame(notes_preview)

"""## 4. Helper: Extract Note Arrays from a MIDI File

"""

def midi_to_notes(midi_file: str) -> pd.DataFrame:
    """Extract pitch, start, end, duration, velocity from the first non-drum instrument."""
    pm = pretty_midi.PrettyMIDI(midi_file)
    instrument = None
    for inst in pm.instruments:
        if not inst.is_drum and len(inst.notes) > 0:
            instrument = inst
            break
    if instrument is None:
        return pd.DataFrame(columns=["pitch", "start", "end", "duration", "velocity"])

    notes = collections.defaultdict(list)
    sorted_notes = sorted(instrument.notes, key=lambda n: n.start)
    prev_start = sorted_notes[0].start if sorted_notes else 0.0

    for note in sorted_notes:
        start = note.start
        end = note.end
        notes["pitch"].append(note.pitch)
        notes["start"].append(start)
        notes["end"].append(end)
        notes["duration"].append(end - start)
        notes["velocity"].append(note.velocity)
        notes["step"].append(start - prev_start)  # time since previous note onset
        prev_start = start

    return pd.DataFrame(notes)

raw_notes = midi_to_notes(sample_file)
print(f"Notes in sample: {len(raw_notes)}")
raw_notes.head(10)

"""## 5. Visualize a Short Excerpt"""

def plot_piano_roll(notes_df: pd.DataFrame, count: int = 100, title: str = "Piano roll"):
    """Simple pitch vs time scatter (piano-roll style)."""
    subset = notes_df.head(count)
    plt.figure(figsize=(14, 5))
    plt.scatter(subset["start"], subset["pitch"], s=10, c=subset["velocity"], cmap="viridis", alpha=0.8)
    plt.xlabel("Time (s)")
    plt.ylabel("MIDI pitch")
    plt.title(title)
    plt.colorbar(label="Velocity")
    plt.tight_layout()
    plt.show()

plot_piano_roll(raw_notes, count=120, title=f"Sample excerpt – {pathlib.Path(sample_file).name}")

"""## 6. Dataset-level Statistics (sample of files)"""

# Use a subset for speed (full pass is fine too, just slower)
N_SAMPLE = min(80, len(filenames))
sample_files = filenames[:N_SAMPLE]

stats = []
all_pitches = []
all_durations = []
all_steps = []

for f in tqdm(sample_files, desc="Scanning MIDI files"):
    try:
        notes = midi_to_notes(f)
        if len(notes) == 0:
            continue
        stats.append({
            "file": pathlib.Path(f).name,
            "n_notes": len(notes),
            "duration_s": notes["end"].max(),
            "pitch_min": notes["pitch"].min(),
            "pitch_max": notes["pitch"].max(),
            "pitch_mean": notes["pitch"].mean(),
            "vel_mean": notes["velocity"].mean(),
        })
        all_pitches.extend(notes["pitch"].tolist())
        all_durations.extend(notes["duration"].tolist())
        all_steps.extend(notes["step"].tolist())
    except Exception as e:
        print(f"Skip {f}: {e}")

stats_df = pd.DataFrame(stats)
print(f"Successfully parsed: {len(stats_df)} files")
display(stats_df.describe().round(2))

"""### Pitch distribution"""

plt.figure(figsize=(12, 4))
sns.histplot(all_pitches, bins=88, color="steelblue")
plt.xlabel("MIDI pitch")
plt.ylabel("Count")
plt.title("Pitch distribution (sampled files)")
plt.tight_layout()
plt.show()

print(f"Pitch range: {min(all_pitches)} – {max(all_pitches)}")
print(f"Most common pitches: {Counter(all_pitches).most_common(8)}")

"""### Duration & step distributions"""

fig, axes = plt.subplots(1, 2, figsize=(14, 4))

# Cap outliers for readable plots
dur_clip = np.clip(all_durations, 0, 2.0)
step_clip = np.clip(all_steps, 0, 1.0)

sns.histplot(dur_clip, bins=50, ax=axes[0], color="darkorange")
axes[0].set_title("Note duration (s, clipped at 2s)")
axes[0].set_xlabel("Duration (s)")

sns.histplot(step_clip, bins=50, ax=axes[1], color="seagreen")
axes[1].set_title("Step (onset gap, s, clipped at 1s)")
axes[1].set_xlabel("Step (s)")

plt.tight_layout()
plt.show()

"""## 7. What We Will Model Later

For the LSTM we typically predict, for each note:

| Feature | Meaning |
|---------|---------|
| **pitch** | MIDI note number (0–127) |
| **step** | Time since previous note onset |
| **duration** | How long the note is held |

Velocity can be included or fixed for simplicity.

Next notebooks will:
1. Encode these into fixed-length sequences  
2. Train an LSTM to predict the next `(pitch, step, duration)`  
3. Sample new sequences and write them back to MIDI

## 8. Quick Summary
"""

print("=== Summary ===")
print(f"MIDI files found     : {len(filenames)}")
print(f"Files scanned        : {len(stats_df)}")
print(f"Total notes (sample) : {len(all_pitches)}")
print(f"Avg notes / file     : {stats_df['n_notes'].mean():.0f}")
print(f"Avg duration (s)     : {stats_df['duration_s'].mean():.1f}")
print(f"Pitch range          : {min(all_pitches)} – {max(all_pitches)}")
print("\nReady for preprocessing → training → generation.")